In [5]:
import pandas as pd
import torch
from pandas import DataFrame

raw_data = pd.read_excel('../data/final.xlsx')
solar_data = pd.read_excel('../data/solar.xlsx')
water_data = pd.read_excel('../data/water.xlsx')
wind_data = pd.read_excel('../data/wind.xlsx')

In [6]:
def reduce_solar(province:str):
    province_df = raw_data[raw_data['name']==province]
    solar_after_data = solar_data[solar_data['province']==province]
    solar_after_data['Year'] = solar_after_data['year'] % 100
    solar_after_data['Month'] = solar_after_data['month']
    solar_train = pd.merge(province_df,solar_after_data,how="right",on=['Year','Month'])
    solar_train = solar_train[['100 metre U wind component(m/s)',
                               '100 metre V wind component(m/s)', '2 metre dewpoint temperature(K)',
                               '2 metre temperature(K)', 'Surface runoff(m)', 'Runoff(m)',
                               'Surface net short-wave (solar) radiation(J/m²)', '乘以面积(J)',
                               'Surface short-wave (solar) radiation downward clear-sky(J/m²)',
                               '乘以面积(J).1', 'Surface short-wave (solar) radiation downwards(J/m²)',
                               '乘以面积(J).2','日发电系数']]
    
    return solar_train

df = reduce_solar("上海")
df

/var/folders/p8/ztd8kwkj247249w0h6_9g2rc0000gn/T/ipykernel_78018/471711592.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  solar_after_data['Year'] = solar_after_data['year'] % 100
/var/folders/p8/ztd8kwkj247249w0h6_9g2rc0000gn/T/ipykernel_78018/471711592.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  solar_after_data['Month'] = solar_after_data['month']


100 metre U wind component(m/s)  100 metre V wind component(m/s)  \
0                            0.849450                         2.094218   
1                           -0.683009                         9.178101   
2                            4.168527                        -5.582550   
3                           -4.113223                         0.576815   
4                           -1.479465                         3.585007   
...                               ...                              ...   
1511                         1.195356                         0.991302   
1512                         6.363928                        -1.766412   
1513                        -1.403384                         0.602293   
1514                         1.089871                        -4.249984   
1515                         2.677802                        -6.793048   

      2 metre dewpoint temperature(K)  2 metre temperature(K)  \
0                          272.524957              276.618472   
1                          281.331841              284.559003   
2                          279.025636              281.462258   
3                          275.930926              281.135115   
4                          280.103396              282.011059   
...                               ...                     ...   
1511                       282.212186              286.703971   
1512                       280.033994              285.951530   
1513                       279.178773              285.422762   
1514                       281.214023              287.518909   
1515                       272.260165              280.878416   

      Surface runoff(m)  Runoff(m)  \
0          0.000000e+00   0.000268   
1          6.508827e-06   0.000275   
2          1.192093e-06   0.000269   
3          1.057386e-05   0.000278   
4          1.764297e-06   0.000268   
...                 ...        ...   
1511       7.152557e-08   0.000407   
1512       0.000000e+00   0.000402   
1513       0.000000e+00   0.000397   
1514       0.000000e+00   0.000392   
1515       0.000000e+00   0.000387   

      Surface net short-wave (solar) radiation(J/m²)       乘以面积(J)  \
0                                         10250758.4  6.499493e+16   
1                                          5823257.6  3.692236e+16   
2                                         10950476.8  6.943150e+16   
3                                          7991148.8  5.066788e+16   
4                                          9957862.4  6.313783e+16   
...                                              ...           ...   
1511                                      10299820.8  6.530601e+16   
1512                                      11522406.4  7.305782e+16   
1513                                      11242624.0  7.128386e+16   
1514                                      10294067.2  6.526953e+16   
1515                                      11296230.4  7.162375e+16   

      Surface short-wave (solar) radiation downward clear-sky(J/m²)  \
0                                            14935942.4               
1                                            14162118.4               
2                                            15387795.2               
3                                            15045427.2               
4                                            15350227.2               
...                                                 ...               
1511                                         12924486.4               
1512                                         13133056.0               
1513                                         12800256.0               
1514                                         12725222.4               
1515                                         13260755.2               

         乘以面积(J).1  Surface short-wave (solar) radiation downwards(J/m²)  \
0     9.470134e+16                                         11523232.0      
1     8.979491e+16               

In [7]:
continuous_cols = ['100 metre U wind component(m/s)',
                   '100 metre V wind component(m/s)', '2 metre dewpoint temperature(K)',
                   '2 metre temperature(K)', 'Surface runoff(m)', 'Runoff(m)',
                   'Surface net short-wave (solar) radiation(J/m²)', '乘以面积(J)',
                   'Surface short-wave (solar) radiation downward clear-sky(J/m²)',
                   '乘以面积(J).1', 'Surface short-wave (solar) radiation downwards(J/m²)',
                   '乘以面积(J).2'] 

In [8]:
import torch
import numpy as np

numpy_array = df.to_numpy()
train_data = torch.tensor(numpy_array)
train_data

tensor([[ 8.4945e-01,  2.0942e+00,  2.7252e+02,  ...,  1.1523e+07,
          7.3063e+16,  1.0847e+00],
        [-6.8301e-01,  9.1781e+00,  2.8133e+02,  ...,  6.5452e+06,
          4.1500e+16,  1.0847e+00],
        [ 4.1685e+00, -5.5826e+00,  2.7903e+02,  ...,  1.2312e+07,
          7.8061e+16,  1.0847e+00],
        ...,
        [-1.4034e+00,  6.0229e-01,  2.7918e+02,  ...,  1.2682e+07,
          8.0411e+16,  3.7335e+00],
        [ 1.0899e+00, -4.2500e+00,  2.8121e+02,  ...,  1.1612e+07,
          7.3623e+16,  3.7335e+00],
        [ 2.6778e+00, -6.7930e+00,  2.7226e+02,  ...,  1.2755e+07,
          8.0875e+16,  3.7335e+00]], dtype=torch.float64)

In [66]:
train_data.shape

torch.Size([1516, 13])

In [77]:
train_data.shape

torch.Size([1516, 13])

# 下面是 dataset 类的测试

In [1]:
from Dataset import MyDataset

dataset = MyDataset("上海")

/Users/wxk/DataspellProjects/ml/energy/Dataset.py:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  solar_after_data['Year'] = solar_after_data['year'] % 100
/Users/wxk/DataspellProjects/ml/energy/Dataset.py:19: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  solar_after_data['Month'] = solar_after_data['month']


In [10]:
train,traget = dataset[1]
len(train)

12

In [9]:
train_data[1,:]

tensor([-6.8301e-01,  9.1781e+00,  2.8133e+02,  2.8456e+02,  6.5088e-06,
         2.7523e-04,  5.8233e+06,  3.6922e+16,  1.4162e+07,  8.9795e+16,
         6.5452e+06,  4.1500e+16,  1.0847e+00], dtype=torch.float64)

# 下面是多层感知机的实现

In [1]:
import torch.optim
from Dataset import MyDataset
from torch.utils.data import DataLoader
from Model import MLP
from torch.nn import MSELoss

dataset = MyDataset("上海")
dataloader = DataLoader(dataset,batch_size=1)

/Users/wxk/DataspellProjects/ml/energy/Dataset.py:23: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  solar_after_data['Year'] = solar_after_data['year'] % 100
/Users/wxk/DataspellProjects/ml/energy/Dataset.py:24: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  solar_after_data['Month'] = solar_after_data['month']


In [2]:
dataset[1]

(tensor([-6.8301e-01,  9.1781e+00,  2.8133e+02,  2.8456e+02,  6.5088e-06,
          2.7523e-04,  5.8233e+06,  3.6922e+16,  1.4162e+07,  8.9795e+16,
          6.5452e+06,  4.1500e+16], dtype=torch.float64),
 tensor(1.0847, dtype=torch.float64))